import re
import requests
import sys
from PyQt5.QtGui import QIcon

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowIcon(QIcon("D:/PyCharm 2020.1.5/QT/img/xiaolong.ico"))
        MainWindow.resize(859, 631)
        MainWindow.setStyleSheet("background-color: rgb(235, 235, 235);")
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(730, 0, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(700, 60, 141, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 330, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(702, 317, 131, 61))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 20, 571, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(112, 80, 571, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(110, 170, 571, 391))
        self.textBrowser.setObjectName("textBrowser")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(740, 120, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(700, 190, 141, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(730, 480, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 160, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(730, 530, 91, 31))
        self.textBrowser_2.setStyleSheet("border:none;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(9, 210, 91, 31))
        self.textBrowser_3.setAcceptDrops(True)
        self.textBrowser_3.setStyleSheet("border: none;")
        self.textBrowser_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textBrowser_3.setObjectName("textBrowser_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 859, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.pushButton.clicked.connect(self.Sipder)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FOFA_URL"))
        self.label.setText(_translate("MainWindow", "URL:"))
        self.label_2.setText(_translate("MainWindow", "COOKIE:"))
        self.label_3.setText(_translate("MainWindow", "页数"))
        self.comboBox.setItemText(0, _translate("MainWindow", "6"))
        self.comboBox.setItemText(1, _translate("MainWindow", "非会员只能爬取6页"))
        self.comboBox.setItemText(2, _translate("MainWindow", "12"))
        self.comboBox.setItemText(3, _translate("MainWindow", "24"))
        self.comboBox.setItemText(4, _translate("MainWindow", "48"))
        self.comboBox.setItemText(5, _translate("MainWindow", "96"))
        self.comboBox.setItemText(6, _translate("MainWindow", "192"))
        self.comboBox.setItemText(7, _translate("MainWindow", "224"))
        self.comboBox.setItemText(8, _translate("MainWindow", "1000"))
        self.comboBox.setItemText(9, _translate("MainWindow", "5000"))
        self.comboBox.setItemText(10, _translate("MainWindow", "8000"))
        self.label_4.setText(_translate("MainWindow", "输出:"))
        self.pushButton.setText(_translate("MainWindow", "一键爬取资产"))
        self.label_5.setText(_translate("MainWindow", "城市"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "四川"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "上海"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "海南"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "福建"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "海南"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "北京"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "河北"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "河南"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "广西"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "广东"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "山东"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "山西"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "陕西"))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "云南"))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "浙江"))
        self.comboBox_2.setItemText(15, _translate("MainWindow", "安徽"))
        self.comboBox_2.setItemText(16, _translate("MainWindow", "湖南"))
        self.comboBox_2.setItemText(17, _translate("MainWindow", "湖北"))
        self.comboBox_2.setItemText(18, _translate("MainWindow", "江苏"))
        self.comboBox_2.setItemText(19, _translate("MainWindow", "辽宁"))
        self.comboBox_2.setItemText(20, _translate("MainWindow", "吉林"))
        self.comboBox_2.setItemText(21, _translate("MainWindow", "青海"))
        self.comboBox_2.setItemText(22, _translate("MainWindow", "黑龙江"))
        self.comboBox_2.setItemText(23, _translate("MainWindow", "天津"))
        self.comboBox_2.setItemText(24, _translate("MainWindow", "江西"))
        self.comboBox_2.setItemText(25, _translate("MainWindow", "未知"))
        self.label_6.setText(_translate("MainWindow", "爬取总数"))
        self.label_7.setText(_translate("MainWindow", "完成状态"))

    def Sipder(self):
        self.count = 0
        self.textBrowser.setText("")
        self.textBrowser_2.setText(str(self.count))
        try:
            url = self.lineEdit.text()
            print(url)
            cookie = self.lineEdit_2.text()
            print(cookie)
            page = self.comboBox.currentText()
            print(page)
            for i in range(1, int(page) + 1):

                self.textBrowser_3.setText("爬取中...")
                self.textBrowser_3.setStyleSheet("color: rgb(255, 0, 0);")
                print(i)
                url1 = str(url) + "&page=" + str(i) + "&page_size=10"
                header = {
                    "Cookie": str(cookie)
                }
                html = requests.get(url=url1, headers=header)
                url_list = re.findall('<a href="(http.*?)"', html.text)
                for i in url_list:
                    self.count += 1
                    self.write(i)

        except:
            self.textBrowser.append("程序异常请联系开发者10086")
            self.textBrowser_3.setText("异常...")
        self.status()

    def status(self):
        self.textBrowser_2.setText(str(self.count) + "个url")
        self.textBrowser_3.setText("爬取完成")
        self.textBrowser_3.setStyleSheet("color: rgb(0, 170, 0);")

    def write(self, text):
        self.textBrowser.append(str(text))  # 在指定的区域显示提示信息
        self.cursor = self.textBrowser.textCursor()
        self.textBrowser.moveCursor(self.cursor.End)  # 光标移到最后，这样就会自动显示出来
        QtWidgets.QApplication.processEvents()  # 一定加上这个功能，不然有卡顿


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
